### ISSUE TITLE
Write conclusion

### ISSUE THREAD

**Issue by Lundbrik** [ahovgaard/TiPL-kleenex-approx#14]
I have started a bit on the conclusion, not quite sure what to write though

**Comment by Ginko-X** [comment]
Here is some of my opinion:

- our experiment result shows the complexity of approximate kleenex goes too large (and some other problem like cache usage), and is not practical for real world approximate matching because there are many limitations on using it, such as k<=2 or the pattern can only be short ones.   It could be some implementation problems (such as coding) as the theory seems no problem (? maybe). It is worth investigating further and optimize it to make it more practical.

- For approximate matching problem, kleenex can try to be more flexible to patterns just like NR-grep, dealing with different patterns (depending on the length or the  number of errors) with different methods

**Comment by Lundbrik** [comment]
I've fleshed it out some more, anything else you think should be added?

**Comment by ahovgaard** [comment]
I'll also take a look now.

**Comment by ahovgaard** [comment]
I can't really think of what to add.

**Comment by Lundbrik** [comment]
So it seems we're about done. Anything to add, or should we just turn in?

**Comment by Ginko-X** [comment]
Nothing to add  👍

**Comment by ahovgaard** [comment]
Yeah, I guess it's okay to hand it in now. Who'll do it?

**Comment by Lundbrik** [comment]
I just did, but it's probably fine if you do it too.

**Comment by ahovgaard** [comment]
Nice ! 🥇
