### ISSUE TITLE
Split the rest project work?

### ISSUE THREAD

**Issue by Ginko-X** [ahovgaard/TiPL-kleenex-approx#3]
It seems we are doing similar/overlapping work. I think the experiments can be done just by one group member independently and nicely.  

So I have a rough idea of splitting the project work into three parts:

1.  Experiment
- Test the four tools as we discussed last time 
- Show the results in a readable way (like tables or plots)

2. Problem Analysis
- The problem with approximate kleenex (too long compiling time? Performance? and so on)
- The problem with the bachelors' projects
- Other interesting problems
 
3. Proposal/Survey
- other approximate matching techniques (with Kleenex)
- possibility of approximate transduction in Kleenex 
- other interesting things related to the project 

Part 2 and 3 are open and I think they will mainly depend on the responsible member's interesting, but others can also help suggest some ideas.  Since we only have two weeks left, it may not be possible for all of us to investigate them in-depth. So splitting the work could give each of us better focus/understanding in-depth with one respect of the project.  And we can learn the other parts from partners' result.

What do you think about this suggestion?

**Comment by ahovgaard** [comment]
I think the experiments shouldn't take too much work, but that the later parts depends on it. We have more or less functioning benchmark scripts for `kleenex` and `NR-grep`, and a basic plotting script, so I think we should finish run these and plot the results as soon as possible. One person can do this, because it's not too easy to split up more anyway.

I guess some of the other tasks can be further divided and started already, for instance, the review of approximate matching techniques. I think we should put more focus on how to potentially fix the problems, e.g. consider how one could concretely add counting of mismatches to the automata.
